name: go vet test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:

  statictest:
    runs-on: ubuntu-latest
    container: golang:1.21
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download autotests binary
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests-bin
<<<<<<< HEAD
#          fileName: statictest
#          out-file-path: .tools
          latest: true
=======
          latest: true 
          fileName: statictest
          out-file-path: .tools
>>>>>>> 7ff831a2e54e7746e7afbed7ddce23eeeb6ed2ae

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Run statictest
        run: |
          go vet -vettool=$(which statictest) ./...
